repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, staging, --branch, master, --branch, main]
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: check-json
